services:
  jira-oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - ./oracle/init:/container-entrypoint-initdb.d

  jira-kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0"
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: HOST://:9092,DOCKER://:19092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://jira-kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0


  jira-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      _JAVA_OPTIONS: "-XX:UseSVE=0"

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: jira-kafka:19092
    depends_on:
      - jira-kafka

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://jira-elasticsearch:9200
    depends_on:
      - jira-elasticsearch
